apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fluent-bit
  namespace: argocd

spec:
  project: default

  sources:
    - repoURL: https://fluent.github.io/helm-charts
      chart: fluent-bit
      targetRevision: 0.19.0
      helm:
        releaseName: fluent-bit
        valueFiles:
          - $values/gitops/apps/fluent-bit/values.yaml

    - repoURL: https://github.com/AreebC/Fast-API.git
      targetRevision: main
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true