deploymentMode: SingleBinary

memberlist:
  service:
    publishNotReadyAddresses: true

loki:
  enabled: true

  auth_enabled: false

  commonConfig:
    replication_factor: 1

  storage:
    type: s3
    bucketNames:
      chunks: fastapi-project-bucket-1
      ruler: fastapi-project-bucket-2
      admin: fastapi-project-bucket-3
    s3:
      region: us-east-1
      endpoint: s3.amazonaws.com

  schemaConfig:
    configs:
      - from: "2024-01-01"
        store: boltdb-shipper
        object_store: s3
        schema: v13
        index:
          prefix: index_
          period: 24h

  compactor:
    retention_enabled: true
    retention_delete_delay: 2h
    retention_delete_worker_count: 2
    delete_request_store: s3

  limits_config:
    retention_period: 168h
    allow_structured_metadata: false

  ruler:
    storage:
      type: s3
      s3:
        region: us-east-1
        endpoint: s3.amazonaws.com

singleBinary:
  replicas: 1

  persistence:
    enabled: true
    size: 10Gi
    storageClass: gp3

  resources:
    requests:
      cpu: 250m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

backend:
  replicas: 0

read:
  replicas: 0

write:
  replicas: 0

serviceAccount:
  create: false
  name: loki-sa

service:
  type: ClusterIP
  port: 3100

chunksCache:
  enabled: false

resultsCache:
  enabled: false